import { board } from "./board/viewBoard.js";
import { viewsSettings } from "./settings/viewSettings.js";
import { viewMenu } from "./menu/viewMenu.js";
import { viewTable } from "./table/viewTable.js";
import { viewRating } from "./rating/view/viewRating.js";
board;
viewsSettings;
viewMenu;
viewTable;
viewRating;
